server:
  port: 8080
#Spring配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/21game?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 199154000
    driver-class-name: com.mysql.cj.jdbc.Driver
    #ORM
  jpa:
    #创建表使用的数据库引擎默认MyISAM
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true